### ISSUE TITLE
"," in items params bug

### ISSUE THREAD

**Issue by lukascer** [dockwa/simple-react-validator#384]
Array in params is joined with commas first, then split afterwards by commas. Please fix.

It creates an issue when there is a comma in any item of the array (i.e. rule 'in') and therefore validation fails.

![screenValidatorError2](https://user-images.githubusercontent.com/24225019/157254789-5bbc5481-96f0-44d3-85a5-60179bff1edd.PNG)
![screenValidatorError](https://user-images.githubusercontent.com/24225019/157254806-df37dfb1-10b9-4154-aa76-86746bb135f0.PNG)

**Comment by stuyam** [comment]
Can you show me an example of the exact code you are using?

**Comment by lukascer** [comment]
code:
helperText={validator.current.message(
                   "operator1",
                   **docDataState.operator**,
                   `in:${**comboBoxOptions.operator**}|required`
}

values:
docDataState.operator: "České dráhy, a.s."
comboBoxOptions.operator: array that includes ["České dráhy, a.s."]

**Comment by stuyam** [comment]
So the way to get around that when you might have commas or pipes that might confuse Simple React Validator you can use the json syntax for defining rules: https://github.com/dockwa/simple-react-validator#rules for example instead of this `'required|in:stu,stuart,stuyam'` you can do this `['required', {in: ['stu', 'stuyam']}]`

**Comment by lukascer** [comment]
Thank you Stuyam, I just tried what you suggested and it works! 

This solved the issue:
![image](https://user-images.githubusercontent.com/24225019/157643114-9cbcf23d-97f2-4123-90c5-d83fafc9b2f3.png)
