### ISSUE TITLE
Change of language

### ISSUE THREAD

**Issue by SteiNNx** [dockwa/simple-react-validator#62]
Hello, is there any way to change the language? I was manually changing the messages ..

**Comment by SteiNNx** [comment]
to Spanish for example

**Comment by stuyam** [comment]
Currently there is no way of setting the language to something other than English out of the box. Currently the best way to do this would be to set all the messages in your preferred language. For example:
```jsx
this.validator = new SimpleReactValidator({
  messages: {
    email: 'That is not an email.',
    phone: 'That is not a phone.'
  }
}
```

Then since you don't want to do that every time I would make a factory helper to have default config:
```jsx
// save somewhere else
var validatorFactory = function(options = {}) {
  return new SimpleReactValidator({
    messages: {
      email: 'That is not an email.',
      phone: 'That is not a phone.'
    },
    ...options
  })
}

// use in the file you are doing validation
this.validator = validatorFactory()
```

So for now that is the best option. However going forward, are you looking for a Spanish translated version to pull in, or are you looking for something that will automatically localize? Because being able to have it build a bunch of translated versions wouldn't be that hard. Definitely something I would like to have on the roadmap because it has come up before too.

**Comment by SteiNNx** [comment]
thank you .. I realized, anyway, copy the code and transfer it to my language thank you very much!
